version: '3.8'

services:
  magic-mirror:
    build: .
    # Use host networking so ARP (presence detection) can see LAN devices.
    # NOTE: Works only on Linux. Remove this if deploying on non-Linux environments.
    network_mode: host
    # Port mapping unnecessary with host networking; the app will listen directly on :8050
    # ports:
    #   - "8050:8050"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./credentials:/app/credentials
      - ./.env:/app/.env:ro
      - ./magic-mirror-cache:/root/.cache/magic_mirror
    # Optional: ensure raw socket capability (usually present for root already)
    cap_add:
      - NET_RAW
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
